# Generated by Django 4.0.10 on 2026-06-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplemodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='simplepage',
            name='selected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
